# Generated by Django 4.2.3 on 2023-09-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_report', '0019_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=50, verbose_name='納品先会社名')),
                ('delivery_code', models.IntegerField(verbose_name='納品先コード')),
            ],
            options={
                'verbose_name': '納品先',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(default='', max_length=10, verbose_name='ロッド番号')),
                ('stocks', models.IntegerField(verbose_name='在庫数')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='引き継ぎメモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_stock_set', to=settings.AUTH_USER_MODEL, verbose_name='検査担当ユーザー名')),
                ('molding_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molding_stock_set', to=settings.AUTH_USER_MODEL, verbose_name='成形担当ユーザー名')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_report.products', verbose_name='製品名')),
            ],
            options={
                'verbose_name': '在庫',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_day', models.DateField(verbose_name='出荷日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.delivery', verbose_name='納品先情報')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.stock', verbose_name='在庫情報')),
            ],
            options={
                'verbose_name': '出荷',
                'db_table': 'shipping',
            },
        ),
        migrations.CreateModel(
            name='Molding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(default='', max_length=10, verbose_name='ロッド番号')),
                ('good_molding', models.IntegerField(verbose_name='優良成形数')),
                ('bad_molding', models.IntegerField(verbose_name='不良成形数')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='引き継ぎメモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_report.products', verbose_name='製品名')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成形担当ユーザー名')),
            ],
            options={
                'verbose_name': '成形品',
                'db_table': 'molding',
            },
        ),
    ]
