# Generated by Django 4.2.3 on 2023-09-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=50, verbose_name='納品先会社名')),
                ('delivery_code', models.IntegerField(verbose_name='納品先コード')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Molding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField(verbose_name='ロッドナンバー')),
                ('good_molding', models.IntegerField(verbose_name='優良成形数')),
                ('bat_molding', models.IntegerField(verbose_name='不良成形数')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='成形メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_report.products', verbose_name='製品名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
            options={
                'db_table': 'molding',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('molding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='product_management.molding', verbose_name='成形品情報')),
                ('total', models.IntegerField(verbose_name='製品合計数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_day', models.DateField(verbose_name='出荷日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.delivery', verbose_name='納品先情報')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.stock', verbose_name='在庫情報')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
    ]
