# Generated by Django 4.2.3 on 2023-09-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molding',
            options={'verbose_name': '成形品'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': '出荷'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '在庫'},
        ),
    ]
