# Generated by Django 4.2.3 on 2023-09-23 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='molding_time',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), verbose_name='成形日時'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='検査日時'),
        ),
    ]
