# Generated by Django 4.2.3 on 2023-09-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0019_report_status'),
        ('product_management', '0002_stock_molding_time_alter_stock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='daily_report.products', verbose_name='製品名'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipments_required',
            field=models.IntegerField(default=0, verbose_name='出荷必要数'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.delivery', verbose_name='納品先'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.stock', verbose_name='必要ロッドナンバー'),
        ),
    ]
