# Generated by Django 4.2.3 on 2023-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_shipping_product_shipping_shipments_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_code',
            field=models.CharField(max_length=10, verbose_name='納品先コード'),
        ),
    ]
