# Generated by Django 4.2.3 on 2023-09-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_rename_bat_molding_molding_bad_molding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molding',
            name='lot_number',
            field=models.CharField(default='', max_length=10, verbose_name='ロッド番号'),
        ),
    ]
