# Generated by Django 4.2.3 on 2023-09-18 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_report', '0018_alter_report_business_alter_report_product_and_more'),
        ('product_management', '0005_alter_molding_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molding',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_report.products', verbose_name='製品名'),
        ),
        migrations.AlterField(
            model_name='molding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
