# Generated by Django 4.2.3 on 2023-09-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0006_alter_molding_product_alter_molding_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molding',
            name='user',
        ),
        migrations.AddField(
            model_name='molding',
            name='molding_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成形担当ユーザー名'),
        ),
        migrations.AlterField(
            model_name='molding',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='引き継ぎメモ'),
        ),
    ]
