# Generated by Django 4.2.3 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0023_alter_report_good_product'),
        ('product_management', '0008_alter_shipping_shipments_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.delivery', verbose_name='納品先'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='daily_report.products', verbose_name='製品名'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='stock1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock1_set', to='product_management.stock', verbose_name='使用在庫1'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='stock2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock2_set', to='product_management.stock', verbose_name='使用在庫2'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='stock3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock3_set', to='product_management.stock', verbose_name='使用在庫3'),
        ),
    ]
