# Generated by Django 4.2.3 on 2023-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='携帯番号'),
        ),
    ]
