# Generated by Django 4.2.3 on 2023-09-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='業務名')),
                ('business_content', models.CharField(max_length=255, verbose_name='業務内容')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departments', verbose_name='部署情報')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='製品名')),
                ('code', models.IntegerField(verbose_name='製品コード')),
                ('quantity', models.IntegerField(verbose_name='製品取り数')),
                ('pictures', models.FileField(upload_to='product_pictures/', verbose_name='製品画像')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='製品メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_time', models.DateTimeField(blank=True, null=True, verbose_name='作業時間')),
                ('good_product_total', models.IntegerField(blank=True, null=True, verbose_name='優良合計数')),
                ('bad_product_total', models.IntegerField(blank=True, null=True, verbose_name='不良合計数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('busines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_report.business', verbose_name='業務内容')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_report.products', verbose_name='製品情報')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
