# Generated by Django 4.2.3 on 2023-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='operation_time',
        ),
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
