# Generated by Django 4.2.3 on 2023-09-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0002_remove_report_operation_time_report_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
    ]
