# Generated by Django 4.2.3 on 2023-09-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0005_rename_busines_report_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bad_product_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='不良数'),
        ),
        migrations.AlterField(
            model_name='report',
            name='good_product_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='優良数'),
        ),
    ]
