# Generated by Django 4.2.3 on 2023-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0007_alter_products_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pictures',
        ),
        migrations.AddField(
            model_name='report',
            name='lot_nubmer',
            field=models.CharField(default='DEFAULT_VALUE_HERE', max_length=10, verbose_name='ロッド番号'),
        ),
    ]
