# Generated by Django 4.2.3 on 2023-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0009_alter_report_lot_nubmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lot_nubmer',
            field=models.CharField(default='', max_length=10, verbose_name='ロッド番号'),
        ),
    ]
