# Generated by Django 4.2.3 on 2023-09-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0010_alter_report_lot_nubmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='lot_nubmer',
            new_name='lot_number',
        ),
    ]
