# Generated by Django 4.2.3 on 2023-09-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0011_rename_lot_nubmer_report_lot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pictures',
            field=models.FileField(null=True, upload_to='product_pictures', verbose_name='製品画像'),
        ),
    ]
