# Generated by Django 4.2.3 on 2023-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0012_products_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='製品メモ'),
        ),
    ]
