# Generated by Django 4.2.3 on 2023-09-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0014_rename_bad_product_total_report_bad_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='引き継ぎ'),
        ),
    ]
