# Generated by Django 4.2.3 on 2023-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0016_alter_report_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='引き継ぎ'),
        ),
    ]
