# Generated by Django 4.2.3 on 2023-09-18 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_report', '0017_alter_report_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_report.business', verbose_name='業務内容'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_report.products', verbose_name='製品情報'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
