# Generated by Django 4.2.3 on 2023-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0020_alter_report_good_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bad_product',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='不良数'),
        ),
    ]
