# Generated by Django 4.2.3 on 2023-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0021_alter_report_bad_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bad_product',
            field=models.IntegerField(blank=True, null=True, verbose_name='不良数'),
        ),
    ]
